# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            #外网IP：47.244.118.28 内网：172.31.108.220，建议使用内网IP，本地开发可以使用外网IP，但不要提交
#            master:
#                url: jdbc:mysql://47.244.118.28:3306/bfw_manage_dev_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: bfw_manage_dev_db
#                password: dIsfwkl192Kdla
#            # 从库数据源
#            slave:
#                # 从数据源开关/默认关闭
#                enabled: true
#                url: jdbc:mysql://47.244.118.28:3306/sportdata?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#                username: score
#                password: OtZ4RceecexG
#            # 从库数据源
#            db2:
#                # 从数据源开关/默认关闭
#                enabled: true
#                url: jdbc:mysql://47.244.118.28:3306/backend_jmf_com?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#                username: score
#                password: OtZ4RceecexG
            master:
                url: jdbc:mysql://172.16.6.125:3306/bfw_manage_dev_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 123456
                # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: true
                url: jdbc:mysql://47.244.118.28:3306/sportdata?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
                username: score
                password: OtZ4RceecexG
            # 从库数据源
            db2:
                # 从数据源开关/默认关闭
                enabled: true
                url: jdbc:mysql://172.16.6.125:3306/backend_jmf_com?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 123456
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: 
                login-password: 
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

base:
  url: http://gw.dev.qiutx.com/jmfen-sport-usercenter/